# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Consul
      include ConsulAclAuthMethod
      include ConsulAclBindingRule
      include ConsulAclPolicy
      include ConsulAclRole
      include ConsulAclRolePolicyAttachment
      include ConsulAclToken
      include ConsulAclTokenPolicyAttachment
      include ConsulAclTokenRoleAttachment
      include ConsulAdminPartition
      include ConsulAgentService
      include ConsulAutopilotConfig
      include ConsulCatalogEntry
      include ConsulCertificateAuthority
      include ConsulConfigEntry
      include ConsulConfigEntryServiceDefaults
      include ConsulConfigEntryServiceIntentions
      include ConsulConfigEntryServiceResolver
      include ConsulConfigEntryServiceRouter
      include ConsulConfigEntryServiceSplitter
      include ConsulConfigEntryV2ExportedServices
      include ConsulIntention
      include ConsulKeyPrefix
      include ConsulKeys
      include ConsulLicense
      include ConsulNamespace
      include ConsulNamespacePolicyAttachment
      include ConsulNamespaceRoleAttachment
      include ConsulNetworkArea
      include ConsulNode
      include ConsulPeering
      include ConsulPeeringToken
      include ConsulPreparedQuery
      include ConsulService
    end
  end
end
