# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclRole
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_role,
      attributes_class: Consul::Types::AclRoleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :namespace, :node_identities, :partition, :policies, :service_identities, :templated_policies]
  end
  module Consul
    include ConsulAclRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
