# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_config_entry/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulConfigEntry
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_config_entry,
      attributes_class: Consul::Types::ConfigEntryAttributes,
      outputs: { id: :id },
      map: [:kind, :name],
      map_present: [:config_json, :namespace, :partition]
  end
  module Consul
    include ConsulConfigEntry
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
