# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ConfigEntryAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :kind, T::String
    attribute :name, T::String
    attribute? :config_json, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
  end
end
