# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_catalog_entry/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulCatalogEntry
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_catalog_entry,
      attributes_class: Consul::Types::CatalogEntryAttributes,
      outputs: { id: :id },
      map: [:address, :node],
      map_present: [:service, :token]
  end
  module Consul
    include ConsulCatalogEntry
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
