# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class CatalogEntryAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :address, T::String
    attribute :node, T::String
    attribute? :service, T::Array.of(T::Hash).optional
    attribute? :token, T::String.optional
  end
end
