# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_autopilot_config/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAutopilotConfig
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_autopilot_config,
      attributes_class: Consul::Types::AutopilotConfigAttributes,
      outputs: { id: :id },
      map_present: [:datacenter, :last_contact_threshold, :max_trailing_logs, :redundancy_zone_tag, :server_stabilization_time, :upgrade_version_tag],
      map_bool: [:cleanup_dead_servers, :disable_upgrade_migration]
  end
  module Consul
    include ConsulAutopilotConfig
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
