# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class AutopilotConfigAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute? :cleanup_dead_servers, T::Bool.optional
    attribute? :datacenter, T::String.optional
    attribute? :disable_upgrade_migration, T::Bool.optional
    attribute? :last_contact_threshold, T::String.optional
    attribute? :max_trailing_logs, T::Float.optional
    attribute? :redundancy_zone_tag, T::String.optional
    attribute? :server_stabilization_time, T::String.optional
    attribute? :upgrade_version_tag, T::String.optional
  end
end
