# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_namespace_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulNamespacePolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_namespace_policy_attachment,
      attributes_class: Consul::Types::NamespacePolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:namespace, :policy]
  end
  module Consul
    include ConsulNamespacePolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
