# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_key_prefix/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulKeyPrefix
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_key_prefix,
      attributes_class: Consul::Types::KeyPrefixAttributes,
      outputs: { id: :id },
      map: [:path_prefix],
      map_present: [:namespace, :partition, :subkey, :subkeys, :token]
  end
  module Consul
    include ConsulKeyPrefix
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
