# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class KeyPrefixAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :path_prefix, T::String
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :subkey, T::Array.of(T::Hash).optional
    attribute? :subkeys, T::Hash.optional
    attribute? :token, T::String.optional
  end
end
