# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_network_area/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulNetworkArea
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_network_area,
      attributes_class: Consul::Types::NetworkAreaAttributes,
      outputs: { id: :id },
      map: [:peer_datacenter],
      map_present: [:retry_join, :token],
      map_bool: [:use_tls]
  end
  module Consul
    include ConsulNetworkArea
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
