# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class NetworkAreaAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :peer_datacenter, T::String
    attribute? :retry_join, T::Array.of(T::String).optional
    attribute? :token, T::String.optional
    attribute? :use_tls, T::Bool.optional
  end
end
