# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_namespace_role_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulNamespaceRoleAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_namespace_role_attachment,
      attributes_class: Consul::Types::NamespaceRoleAttachmentAttributes,
      outputs: { id: :id },
      map: [:namespace, :role]
  end
  module Consul
    include ConsulNamespaceRoleAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
