# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_role_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclRolePolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_role_policy_attachment,
      attributes_class: Consul::Types::AclRolePolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:policy, :role_id]
  end
  module Consul
    include ConsulAclRolePolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
