# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_peering/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulPeering
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_peering,
      attributes_class: Consul::Types::PeeringAttributes,
      outputs: { id: :id },
      map: [:peer_name, :peering_token],
      map_present: [:meta, :partition]
  end
  module Consul
    include ConsulPeering
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
