# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclToken
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_token,
      attributes_class: Consul::Types::AclTokenAttributes,
      outputs: { id: :id },
      map_present: [:description, :expiration_time, :namespace, :node_identities, :partition, :policies, :roles, :service_identities, :templated_policies],
      map_bool: [:local]
  end
  module Consul
    include ConsulAclToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
