# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class AclTokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute? :description, T::String.optional
    attribute? :expiration_time, T::String.optional
    attribute? :local, T::Bool.optional
    attribute? :namespace, T::String.optional
    attribute? :node_identities, T::Array.of(T::Hash).optional
    attribute? :partition, T::String.optional
    attribute? :policies, T::Array.of(T::String).optional
    attribute? :roles, T::Array.of(T::String).optional
    attribute? :service_identities, T::Array.of(T::Hash).optional
    attribute? :templated_policies, T::Array.of(T::Hash).optional
  end
end
