# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_node/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulNode
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_node,
      attributes_class: Consul::Types::NodeAttributes,
      outputs: { id: :id },
      map: [:address, :name],
      map_present: [:meta, :partition, :token]
  end
  module Consul
    include ConsulNode
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
