# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_config_entry_service_resolver/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulConfigEntryServiceResolver
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_config_entry_service_resolver,
      attributes_class: Consul::Types::ConfigEntryServiceResolverAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:connect_timeout, :default_subset, :failover, :load_balancer, :meta, :namespace, :partition, :redirect, :request_timeout, :subsets]
  end
  module Consul
    include ConsulConfigEntryServiceResolver
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
