# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ConfigEntryServiceResolverAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute? :connect_timeout, T::String.optional
    attribute? :default_subset, T::String.optional
    attribute? :failover, T::Array.of(T::Hash).optional
    attribute? :load_balancer, T::Array.of(T::Hash).optional
    attribute? :meta, T::Hash.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :redirect, T::Array.of(T::Hash).optional
    attribute? :request_timeout, T::String.optional
    attribute? :subsets, T::Array.of(T::Hash).optional
  end
end
