# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_policy,
      attributes_class: Consul::Types::AclPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :rules],
      map_present: [:datacenters, :description, :namespace, :partition]
  end
  module Consul
    include ConsulAclPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
