# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class AclPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute :rules, T::String
    attribute? :datacenters, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
  end
end
