# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_prepared_query/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulPreparedQuery
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_prepared_query,
      attributes_class: Consul::Types::PreparedQueryAttributes,
      outputs: { id: :id },
      map: [:name, :service],
      map_present: [:datacenter, :dns, :failover, :ignore_check_ids, :near, :node_meta, :service_meta, :session, :stored_token, :tags, :template, :token],
      map_bool: [:connect, :only_passing]
  end
  module Consul
    include ConsulPreparedQuery
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
