# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class PreparedQueryAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute :service, T::String
    attribute? :connect, T::Bool.optional
    attribute? :datacenter, T::String.optional
    attribute? :dns, T::Array.of(T::Hash).optional
    attribute? :failover, T::Array.of(T::Hash).optional
    attribute? :ignore_check_ids, T::Array.of(T::String).optional
    attribute? :near, T::String.optional
    attribute? :node_meta, T::Hash.optional
    attribute? :only_passing, T::Bool.optional
    attribute? :service_meta, T::Hash.optional
    attribute? :session, T::String.optional
    attribute? :stored_token, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :template, T::Array.of(T::Hash).optional
    attribute? :token, T::String.optional
  end
end
