# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_auth_method/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclAuthMethod
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_auth_method,
      attributes_class: Consul::Types::AclAuthMethodAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:config, :config_json, :description, :display_name, :max_token_ttl, :namespace, :namespace_rule, :partition, :token_locality]
  end
  module Consul
    include ConsulAclAuthMethod
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
