# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class AclAuthMethodAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute? :config, T::Hash.optional
    attribute? :config_json, T::String.optional
    attribute? :description, T::String.optional
    attribute? :display_name, T::String.optional
    attribute? :max_token_ttl, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :namespace_rule, T::Array.of(T::Hash).optional
    attribute? :partition, T::String.optional
    attribute? :token_locality, T::String.optional
  end
end
