# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_agent_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAgentService
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_agent_service,
      attributes_class: Consul::Types::AgentServiceAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:port, :tags]
  end
  module Consul
    include ConsulAgentService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
