# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_peering_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulPeeringToken
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_peering_token,
      attributes_class: Consul::Types::PeeringTokenAttributes,
      outputs: { id: :id },
      map: [:peer_name],
      map_present: [:meta, :partition, :server_external_addresses]
  end
  module Consul
    include ConsulPeeringToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
