# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class PeeringTokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :peer_name, T::String
    attribute? :meta, T::Hash.optional
    attribute? :partition, T::String.optional
    attribute? :server_external_addresses, T::Array.of(T::String).optional
  end
end
