# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_config_entry_service_splitter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulConfigEntryServiceSplitter
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_config_entry_service_splitter,
      attributes_class: Consul::Types::ConfigEntryServiceSplitterAttributes,
      outputs: { id: :id },
      map: [:name, :splits],
      map_present: [:meta, :namespace, :partition]
  end
  module Consul
    include ConsulConfigEntryServiceSplitter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
