# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_certificate_authority/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulCertificateAuthority
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_certificate_authority,
      attributes_class: Consul::Types::CertificateAuthorityAttributes,
      outputs: { id: :id },
      map: [:connect_provider],
      map_present: [:config, :config_json]
  end
  module Consul
    include ConsulCertificateAuthority
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
