# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class CertificateAuthorityAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :connect_provider, T::String
    attribute? :config, T::Hash.optional
    attribute? :config_json, T::String.optional
  end
end
