# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulService
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_service,
      attributes_class: Consul::Types::ServiceAttributes,
      outputs: { id: :id },
      map: [:name, :node],
      map_present: [:check, :meta, :namespace, :partition, :port, :tags, :weights],
      map_bool: [:enable_tag_override, :external]
  end
  module Consul
    include ConsulService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
