# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ServiceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute :node, T::String
    attribute? :check, T::Array.of(T::Hash).optional
    attribute? :enable_tag_override, T::Bool.optional
    attribute? :external, T::Bool.optional
    attribute? :meta, T::Hash.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :port, T::Float.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :weights, T::Hash.optional
  end
end
