# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_namespace/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulNamespace
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_namespace,
      attributes_class: Consul::Types::NamespaceAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :meta, :partition, :policy_defaults, :role_defaults]
  end
  module Consul
    include ConsulNamespace
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
