# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class NamespaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :meta, T::Hash.optional
    attribute? :partition, T::String.optional
    attribute? :policy_defaults, T::Array.of(T::String).optional
    attribute? :role_defaults, T::Array.of(T::String).optional
  end
end
