# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_intention/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulIntention
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_intention,
      attributes_class: Consul::Types::IntentionAttributes,
      outputs: { id: :id },
      map: [:action, :destination_name, :source_name],
      map_present: [:description, :destination_namespace, :meta, :source_namespace]
  end
  module Consul
    include ConsulIntention
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
