# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class IntentionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :action, T::String
    attribute :destination_name, T::String
    attribute :source_name, T::String
    attribute? :description, T::String.optional
    attribute? :destination_namespace, T::String.optional
    attribute? :meta, T::Hash.optional
    attribute? :source_namespace, T::String.optional
  end
end
