# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_keys/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulKeys
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_keys,
      attributes_class: Consul::Types::KeysAttributes,
      outputs: { id: :id },
      map_present: [:key, :namespace, :partition, :token]
  end
  module Consul
    include ConsulKeys
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
