# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class KeysAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute? :key, T::Array.of(T::Hash).optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :token, T::String.optional
  end
end
