# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_config_entry_service_defaults/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulConfigEntryServiceDefaults
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_config_entry_service_defaults,
      attributes_class: Consul::Types::ConfigEntryServiceDefaultsAttributes,
      outputs: { id: :id },
      map: [:expose, :name, :protocol],
      map_present: [:balance_inbound_connections, :destination, :envoy_extensions, :external_sni, :local_connect_timeout_ms, :local_request_timeout_ms, :max_inbound_connections, :mesh_gateway, :meta, :mode, :mutual_tls_mode, :namespace, :partition, :transparent_proxy, :upstream_config]
  end
  module Consul
    include ConsulConfigEntryServiceDefaults
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
