# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ConfigEntryServiceDefaultsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :expose, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute :protocol, T::String
    attribute? :balance_inbound_connections, T::String.optional
    attribute? :destination, T::Array.of(T::Hash).optional
    attribute? :envoy_extensions, T::Array.of(T::Hash).optional
    attribute? :external_sni, T::String.optional
    attribute? :local_connect_timeout_ms, T::Float.optional
    attribute? :local_request_timeout_ms, T::Float.optional
    attribute? :max_inbound_connections, T::Float.optional
    attribute? :mesh_gateway, T::Array.of(T::Hash).optional
    attribute? :meta, T::Hash.optional
    attribute? :mode, T::String.optional
    attribute? :mutual_tls_mode, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :transparent_proxy, T::Array.of(T::Hash).optional
    attribute? :upstream_config, T::Array.of(T::Hash).optional
  end
end
