# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_binding_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclBindingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_binding_rule,
      attributes_class: Consul::Types::AclBindingRuleAttributes,
      outputs: { id: :id },
      map: [:auth_method, :bind_name, :bind_type],
      map_present: [:bind_vars, :description, :namespace, :partition, :selector]
  end
  module Consul
    include ConsulAclBindingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
