# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ConfigEntryServiceIntentionsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute? :jwt, T::Array.of(T::Hash).optional
    attribute? :meta, T::Hash.optional
    attribute? :namespace, T::String.optional
    attribute? :partition, T::String.optional
    attribute? :sources, T::Array.of(T::Hash).optional
  end
end
