# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_license/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulLicense
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_license,
      attributes_class: Consul::Types::LicenseAttributes,
      outputs: { id: :id },
      map: [:license],
      map_present: [:datacenter]
  end
  module Consul
    include ConsulLicense
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
