# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_admin_partition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAdminPartition
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_admin_partition,
      attributes_class: Consul::Types::AdminPartitionAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description],
      map_bool: [:disable_gossip]
  end
  module Consul
    include ConsulAdminPartition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
