# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class AdminPartitionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :disable_gossip, T::Bool.optional
  end
end
