# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_acl_token_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulAclTokenPolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_acl_token_policy_attachment,
      attributes_class: Consul::Types::AclTokenPolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:policy, :token_id]
  end
  module Consul
    include ConsulAclTokenPolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
