# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_network_area resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulNetworkArea do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { peer_datacenter: 'test-value' } }

  describe ':consul_network_area' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_network_area', 'test')
        validate_required_attributes(config, [:peer_datacenter])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_network_area('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_network_area)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_network_area('test', required_attrs)

        expect(ref.id).to eq("${consul_network_area.test.id}")
        expect(ref.datacenter).to eq("${consul_network_area.test.datacenter}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_network_area', 'test')
        expect(config).not_to have_key('datacenter')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ retry_join: ['test-value'], token: 'test-value', use_tls: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_network_area', 'full')
        expect(config).to have_key('retry_join')
        expect(config).to have_key('token')
        expect(config).to have_key('use_tls')
      end
    end

    context 'optional attributes' do
      it 'includes retry_join when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('opt', required_attrs.merge(retry_join: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'opt')
        expect(config).to have_key('retry_join')
      end

      it 'omits retry_join when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'minimal')
        expect(config).not_to have_key('retry_join')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'minimal')
        expect(config).not_to have_key('token')
      end
      it 'includes use_tls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('opt', required_attrs.merge(use_tls: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'opt')
        expect(config).to have_key('use_tls')
      end

      it 'omits use_tls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_network_area', 'minimal')
        expect(config).not_to have_key('use_tls')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts use_tls=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_tls: val)
          synth.consul_network_area("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_network_area', "bool_#{val}")
          expect(config['use_tls']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_network_area', 'typed')
        expect(config['peer_datacenter']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_network_area('first', required_attrs)
        synth.consul_network_area('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_network_area')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_network_area,
    method: :consul_network_area,
    required_attrs: { peer_datacenter: 'test-value' },
    expected_outputs: [:id, :datacenter],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: [:use_tls]
end
