# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_intention resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulIntention do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { action: 'test-value', destination_name: 'test-value', source_name: 'test-value' } }

  describe ':consul_intention' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_intention', 'test')
        validate_required_attributes(config, [:action, :destination_name, :source_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_intention('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_intention)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_intention('test', required_attrs)

        expect(ref.id).to eq("${consul_intention.test.id}")
        expect(ref.datacenter).to eq("${consul_intention.test.datacenter}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_intention', 'test')
        expect(config).not_to have_key('datacenter')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', destination_namespace: 'test-value', meta: { 'key1' => 'val1' }, source_namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_intention', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('destination_namespace')
        expect(config).to have_key('meta')
        expect(config).to have_key('source_namespace')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes destination_namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('opt', required_attrs.merge(destination_namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'opt')
        expect(config).to have_key('destination_namespace')
      end

      it 'omits destination_namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'minimal')
        expect(config).not_to have_key('destination_namespace')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes source_namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('opt', required_attrs.merge(source_namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'opt')
        expect(config).to have_key('source_namespace')
      end

      it 'omits source_namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_intention', 'minimal')
        expect(config).not_to have_key('source_namespace')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_intention', 'typed')
        expect(config['action']).to be_a(String)
        expect(config['destination_name']).to be_a(String)
        expect(config['source_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_intention('first', required_attrs)
        synth.consul_intention('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_intention')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_intention,
    method: :consul_intention,
    required_attrs: { action: 'test-value', destination_name: 'test-value', source_name: 'test-value' },
    expected_outputs: [:id, :datacenter],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
