# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', node: 'test-value' } }

  describe ':consul_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_service', 'test')
        validate_required_attributes(config, [:name, :node])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_service('test', required_attrs)

        expect(ref.id).to eq("${consul_service.test.id}")
        expect(ref.address).to eq("${consul_service.test.address}")
        expect(ref.datacenter).to eq("${consul_service.test.datacenter}")
        expect(ref.service_id).to eq("${consul_service.test.service_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_service', 'test')
        expect(config).not_to have_key('address')
        expect(config).not_to have_key('datacenter')
        expect(config).not_to have_key('service_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ check: [{ 'key1' => 'val1' }], enable_tag_override: true, external: true, meta: { 'key1' => 'val1' }, namespace: 'test-value', partition: 'test-value', port: 3.14, tags: ['test-value'], weights: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_service', 'full')
        expect(config).to have_key('check')
        expect(config).to have_key('enable_tag_override')
        expect(config).to have_key('external')
        expect(config).to have_key('meta')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
        expect(config).to have_key('port')
        expect(config).to have_key('tags')
        expect(config).to have_key('weights')
      end
    end

    context 'optional attributes' do
      it 'includes check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(check: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('check')
      end

      it 'omits check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('check')
      end
      it 'includes enable_tag_override when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(enable_tag_override: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('enable_tag_override')
      end

      it 'omits enable_tag_override when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('enable_tag_override')
      end
      it 'includes external when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(external: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('external')
      end

      it 'omits external when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('external')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes weights when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('opt', required_attrs.merge(weights: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'opt')
        expect(config).to have_key('weights')
      end

      it 'omits weights when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_service', 'minimal')
        expect(config).not_to have_key('weights')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_tag_override=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_tag_override: val)
          synth.consul_service("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_service', "bool_#{val}")
          expect(config['enable_tag_override']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts external=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(external: val)
          synth.consul_service("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_service', "bool_#{val}")
          expect(config['external']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_service', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['node']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_service('first', required_attrs)
        synth.consul_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_service,
    method: :consul_service,
    required_attrs: { name: 'test-value', node: 'test-value' },
    expected_outputs: [:id, :address, :datacenter, :service_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_tag_override, :external]
end
