# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_peering_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulPeeringToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { peer_name: 'test-value' } }

  describe ':consul_peering_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_peering_token', 'test')
        validate_required_attributes(config, [:peer_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_peering_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_peering_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_peering_token('test', required_attrs)

        expect(ref.id).to eq("${consul_peering_token.test.id}")
        expect(ref.peering_token).to eq("${consul_peering_token.test.peering_token}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering_token', 'test')
        expect(config).not_to have_key('peering_token')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ meta: { 'key1' => 'val1' }, partition: 'test-value', server_external_addresses: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering_token', 'full')
        expect(config).to have_key('meta')
        expect(config).to have_key('partition')
        expect(config).to have_key('server_external_addresses')
      end
    end

    context 'optional attributes' do
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes server_external_addresses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('opt', required_attrs.merge(server_external_addresses: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'opt')
        expect(config).to have_key('server_external_addresses')
      end

      it 'omits server_external_addresses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering_token', 'minimal')
        expect(config).not_to have_key('server_external_addresses')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:peering_token]
        expect(sensitive_fields).to include(:peering_token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering_token', 'typed')
        expect(config['peer_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering_token('first', required_attrs)
        synth.consul_peering_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_peering_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_peering_token,
    method: :consul_peering_token,
    required_attrs: { peer_name: 'test-value' },
    expected_outputs: [:id, :peering_token],
    sensitive_fields: [:peering_token],
    immutable_fields: [],
    boolean_fields: []
end
