# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_acl_auth_method resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAclAuthMethod do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', type: 'test-value' } }

  describe ':consul_acl_auth_method' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'test')
        validate_required_attributes(config, [:name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_auth_method('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_acl_auth_method)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_auth_method('test', required_attrs)

        expect(ref.id).to eq("${consul_acl_auth_method.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ config: { 'key1' => 'val1' }, config_json: 'test-value', description: 'test-value', display_name: 'test-value', max_token_ttl: 'test-value', namespace: 'test-value', namespace_rule: [{ 'key1' => 'val1' }], partition: 'test-value', token_locality: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_auth_method', 'full')
        expect(config).to have_key('config')
        expect(config).to have_key('config_json')
        expect(config).to have_key('description')
        expect(config).to have_key('display_name')
        expect(config).to have_key('max_token_ttl')
        expect(config).to have_key('namespace')
        expect(config).to have_key('namespace_rule')
        expect(config).to have_key('partition')
        expect(config).to have_key('token_locality')
      end
    end

    context 'optional attributes' do
      it 'includes config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('config')
      end

      it 'omits config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('config')
      end
      it 'includes config_json when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(config_json: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('config_json')
      end

      it 'omits config_json when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('config_json')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes display_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(display_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('display_name')
      end

      it 'omits display_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('display_name')
      end
      it 'includes max_token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(max_token_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('max_token_ttl')
      end

      it 'omits max_token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('max_token_ttl')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes namespace_rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(namespace_rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('namespace_rule')
      end

      it 'omits namespace_rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('namespace_rule')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes token_locality when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('opt', required_attrs.merge(token_locality: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'opt')
        expect(config).to have_key('token_locality')
      end

      it 'omits token_locality when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_auth_method', 'minimal')
        expect(config).not_to have_key('token_locality')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_auth_method', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_auth_method('first', required_attrs)
        synth.consul_acl_auth_method('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_acl_auth_method')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_acl_auth_method,
    method: :consul_acl_auth_method,
    required_attrs: { name: 'test-value', type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
