# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_config_entry_service_resolver resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulConfigEntryServiceResolver do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':consul_config_entry_service_resolver' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_service_resolver('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_config_entry_service_resolver)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_service_resolver('test', required_attrs)

        expect(ref.id).to eq("${consul_config_entry_service_resolver.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ connect_timeout: 'test-value', default_subset: 'test-value', failover: [{ 'key1' => 'val1' }], load_balancer: [{ 'key1' => 'val1' }], meta: { 'key1' => 'val1' }, namespace: 'test-value', partition: 'test-value', redirect: [{ 'key1' => 'val1' }], request_timeout: 'test-value', subsets: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'full')
        expect(config).to have_key('connect_timeout')
        expect(config).to have_key('default_subset')
        expect(config).to have_key('failover')
        expect(config).to have_key('load_balancer')
        expect(config).to have_key('meta')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
        expect(config).to have_key('redirect')
        expect(config).to have_key('request_timeout')
        expect(config).to have_key('subsets')
      end
    end

    context 'optional attributes' do
      it 'includes connect_timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(connect_timeout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('connect_timeout')
      end

      it 'omits connect_timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('connect_timeout')
      end
      it 'includes default_subset when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(default_subset: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('default_subset')
      end

      it 'omits default_subset when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('default_subset')
      end
      it 'includes failover when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(failover: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('failover')
      end

      it 'omits failover when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('failover')
      end
      it 'includes load_balancer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(load_balancer: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('load_balancer')
      end

      it 'omits load_balancer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('load_balancer')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes redirect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(redirect: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('redirect')
      end

      it 'omits redirect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('redirect')
      end
      it 'includes request_timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(request_timeout: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('request_timeout')
      end

      it 'omits request_timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('request_timeout')
      end
      it 'includes subsets when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('opt', required_attrs.merge(subsets: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'opt')
        expect(config).to have_key('subsets')
      end

      it 'omits subsets when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'minimal')
        expect(config).not_to have_key('subsets')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_service_resolver', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_resolver('first', required_attrs)
        synth.consul_config_entry_service_resolver('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_config_entry_service_resolver')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_config_entry_service_resolver,
    method: :consul_config_entry_service_resolver,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
