# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_acl_token_policy_attachment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAclTokenPolicyAttachment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { policy: 'test-value', token_id: 'test-value' } }

  describe ':consul_acl_token_policy_attachment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token_policy_attachment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_acl_token_policy_attachment', 'test')
        validate_required_attributes(config, [:policy, :token_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_token_policy_attachment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_acl_token_policy_attachment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_token_policy_attachment('test', required_attrs)

        expect(ref.id).to eq("${consul_acl_token_policy_attachment.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token_policy_attachment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_token_policy_attachment', 'typed')
        expect(config['policy']).to be_a(String)
        expect(config['token_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token_policy_attachment('first', required_attrs)
        synth.consul_acl_token_policy_attachment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_acl_token_policy_attachment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_acl_token_policy_attachment,
    method: :consul_acl_token_policy_attachment,
    required_attrs: { policy: 'test-value', token_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
