# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_keys resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulKeys do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':consul_keys' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_keys', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_keys('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_keys)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_keys('test', required_attrs)

        expect(ref.id).to eq("${consul_keys.test.id}")
        expect(ref.datacenter).to eq("${consul_keys.test.datacenter}")
        expect(ref.var).to eq("${consul_keys.test.var}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_keys', 'test')
        expect(config).not_to have_key('datacenter')
        expect(config).not_to have_key('var')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ key: [{ 'key1' => 'val1' }], namespace: 'test-value', partition: 'test-value', token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_keys', 'full')
        expect(config).to have_key('key')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('opt', required_attrs.merge(key: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'opt')
        expect(config).to have_key('key')
      end

      it 'omits key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'minimal')
        expect(config).not_to have_key('key')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_keys', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_keys', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_keys('first', required_attrs)
        synth.consul_keys('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_keys')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_keys,
    method: :consul_keys,
    required_attrs: {},
    expected_outputs: [:id, :datacenter, :var],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
