# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_config_entry_service_defaults resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulConfigEntryServiceDefaults do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { expose: [{ 'key1' => 'val1' }], name: 'test-value', protocol: 'test-value' } }

  describe ':consul_config_entry_service_defaults' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'test')
        validate_required_attributes(config, [:expose, :name, :protocol])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_service_defaults('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_config_entry_service_defaults)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_service_defaults('test', required_attrs)

        expect(ref.id).to eq("${consul_config_entry_service_defaults.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ balance_inbound_connections: 'test-value', destination: [{ 'key1' => 'val1' }], envoy_extensions: [{ 'key1' => 'val1' }], external_sni: 'test-value', local_connect_timeout_ms: 3.14, local_request_timeout_ms: 3.14, max_inbound_connections: 3.14, mesh_gateway: [{ 'key1' => 'val1' }], meta: { 'key1' => 'val1' }, mode: 'test-value', mutual_tls_mode: 'test-value', namespace: 'test-value', partition: 'test-value', transparent_proxy: [{ 'key1' => 'val1' }], upstream_config: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'full')
        expect(config).to have_key('balance_inbound_connections')
        expect(config).to have_key('destination')
        expect(config).to have_key('envoy_extensions')
        expect(config).to have_key('external_sni')
        expect(config).to have_key('local_connect_timeout_ms')
        expect(config).to have_key('local_request_timeout_ms')
        expect(config).to have_key('max_inbound_connections')
        expect(config).to have_key('mesh_gateway')
        expect(config).to have_key('meta')
        expect(config).to have_key('mode')
        expect(config).to have_key('mutual_tls_mode')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
        expect(config).to have_key('transparent_proxy')
        expect(config).to have_key('upstream_config')
      end
    end

    context 'optional attributes' do
      it 'includes balance_inbound_connections when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(balance_inbound_connections: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('balance_inbound_connections')
      end

      it 'omits balance_inbound_connections when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('balance_inbound_connections')
      end
      it 'includes destination when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(destination: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('destination')
      end

      it 'omits destination when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('destination')
      end
      it 'includes envoy_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(envoy_extensions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('envoy_extensions')
      end

      it 'omits envoy_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('envoy_extensions')
      end
      it 'includes external_sni when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(external_sni: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('external_sni')
      end

      it 'omits external_sni when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('external_sni')
      end
      it 'includes local_connect_timeout_ms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(local_connect_timeout_ms: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('local_connect_timeout_ms')
      end

      it 'omits local_connect_timeout_ms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('local_connect_timeout_ms')
      end
      it 'includes local_request_timeout_ms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(local_request_timeout_ms: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('local_request_timeout_ms')
      end

      it 'omits local_request_timeout_ms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('local_request_timeout_ms')
      end
      it 'includes max_inbound_connections when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(max_inbound_connections: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('max_inbound_connections')
      end

      it 'omits max_inbound_connections when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('max_inbound_connections')
      end
      it 'includes mesh_gateway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(mesh_gateway: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('mesh_gateway')
      end

      it 'omits mesh_gateway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('mesh_gateway')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('mode')
      end

      it 'omits mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('mode')
      end
      it 'includes mutual_tls_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(mutual_tls_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('mutual_tls_mode')
      end

      it 'omits mutual_tls_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('mutual_tls_mode')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes transparent_proxy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(transparent_proxy: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('transparent_proxy')
      end

      it 'omits transparent_proxy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('transparent_proxy')
      end
      it 'includes upstream_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('opt', required_attrs.merge(upstream_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'opt')
        expect(config).to have_key('upstream_config')
      end

      it 'omits upstream_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'minimal')
        expect(config).not_to have_key('upstream_config')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_service_defaults', 'typed')
        expect(config['expose']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['protocol']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_service_defaults('first', required_attrs)
        synth.consul_config_entry_service_defaults('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_config_entry_service_defaults')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_config_entry_service_defaults,
    method: :consul_config_entry_service_defaults,
    required_attrs: { expose: [{ 'key1' => 'val1' }], name: 'test-value', protocol: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
