# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_prepared_query resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulPreparedQuery do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', service: 'test-value' } }

  describe ':consul_prepared_query' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_prepared_query', 'test')
        validate_required_attributes(config, [:name, :service])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_prepared_query('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_prepared_query)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_prepared_query('test', required_attrs)

        expect(ref.id).to eq("${consul_prepared_query.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ connect: true, datacenter: 'test-value', dns: [{ 'key1' => 'val1' }], failover: [{ 'key1' => 'val1' }], ignore_check_ids: ['test-value'], near: 'test-value', node_meta: { 'key1' => 'val1' }, only_passing: true, service_meta: { 'key1' => 'val1' }, session: 'test-value', stored_token: 'test-value', tags: ['test-value'], template: [{ 'key1' => 'val1' }], token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_prepared_query', 'full')
        expect(config).to have_key('connect')
        expect(config).to have_key('datacenter')
        expect(config).to have_key('dns')
        expect(config).to have_key('failover')
        expect(config).to have_key('ignore_check_ids')
        expect(config).to have_key('near')
        expect(config).to have_key('node_meta')
        expect(config).to have_key('only_passing')
        expect(config).to have_key('service_meta')
        expect(config).to have_key('session')
        expect(config).to have_key('stored_token')
        expect(config).to have_key('tags')
        expect(config).to have_key('template')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes connect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(connect: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('connect')
      end

      it 'omits connect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('connect')
      end
      it 'includes datacenter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(datacenter: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('datacenter')
      end

      it 'omits datacenter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('datacenter')
      end
      it 'includes dns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(dns: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('dns')
      end

      it 'omits dns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('dns')
      end
      it 'includes failover when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(failover: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('failover')
      end

      it 'omits failover when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('failover')
      end
      it 'includes ignore_check_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(ignore_check_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('ignore_check_ids')
      end

      it 'omits ignore_check_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('ignore_check_ids')
      end
      it 'includes near when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(near: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('near')
      end

      it 'omits near when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('near')
      end
      it 'includes node_meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(node_meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('node_meta')
      end

      it 'omits node_meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('node_meta')
      end
      it 'includes only_passing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(only_passing: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('only_passing')
      end

      it 'omits only_passing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('only_passing')
      end
      it 'includes service_meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(service_meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('service_meta')
      end

      it 'omits service_meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('service_meta')
      end
      it 'includes session when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(session: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('session')
      end

      it 'omits session when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('session')
      end
      it 'includes stored_token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(stored_token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('stored_token')
      end

      it 'omits stored_token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('stored_token')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(template: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('template')
      end

      it 'omits template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('template')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_prepared_query', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts connect=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(connect: val)
          synth.consul_prepared_query("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_prepared_query', "bool_#{val}")
          expect(config['connect']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts only_passing=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(only_passing: val)
          synth.consul_prepared_query("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_prepared_query', "bool_#{val}")
          expect(config['only_passing']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_prepared_query', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['service']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_prepared_query('first', required_attrs)
        synth.consul_prepared_query('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_prepared_query')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_prepared_query,
    method: :consul_prepared_query,
    required_attrs: { name: 'test-value', service: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: [:connect, :only_passing]
end
