# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_acl_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAclToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':consul_acl_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_acl_token', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_acl_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_token('test', required_attrs)

        expect(ref.id).to eq("${consul_acl_token.test.id}")
        expect(ref.accessor_id).to eq("${consul_acl_token.test.accessor_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_token', 'test')
        expect(config).not_to have_key('accessor_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', expiration_time: 'test-value', local: true, namespace: 'test-value', node_identities: [{ 'key1' => 'val1' }], partition: 'test-value', policies: ['test-value'], roles: ['test-value'], service_identities: [{ 'key1' => 'val1' }], templated_policies: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_token', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('expiration_time')
        expect(config).to have_key('local')
        expect(config).to have_key('namespace')
        expect(config).to have_key('node_identities')
        expect(config).to have_key('partition')
        expect(config).to have_key('policies')
        expect(config).to have_key('roles')
        expect(config).to have_key('service_identities')
        expect(config).to have_key('templated_policies')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes expiration_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(expiration_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('expiration_time')
      end

      it 'omits expiration_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('expiration_time')
      end
      it 'includes local when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(local: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('local')
      end

      it 'omits local when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('local')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes node_identities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(node_identities: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('node_identities')
      end

      it 'omits node_identities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('node_identities')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('policies')
      end

      it 'omits policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('policies')
      end
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('roles')
      end
      it 'includes service_identities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(service_identities: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('service_identities')
      end

      it 'omits service_identities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('service_identities')
      end
      it 'includes templated_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('opt', required_attrs.merge(templated_policies: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'opt')
        expect(config).to have_key('templated_policies')
      end

      it 'omits templated_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_token', 'minimal')
        expect(config).not_to have_key('templated_policies')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts local=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(local: val)
          synth.consul_acl_token("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_acl_token', "bool_#{val}")
          expect(config['local']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_token', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_token('first', required_attrs)
        synth.consul_acl_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_acl_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_acl_token,
    method: :consul_acl_token,
    required_attrs: {},
    expected_outputs: [:id, :accessor_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:local]
end
