# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_key_prefix resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulKeyPrefix do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { path_prefix: 'test-value' } }

  describe ':consul_key_prefix' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_key_prefix', 'test')
        validate_required_attributes(config, [:path_prefix])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_key_prefix('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_key_prefix)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_key_prefix('test', required_attrs)

        expect(ref.id).to eq("${consul_key_prefix.test.id}")
        expect(ref.datacenter).to eq("${consul_key_prefix.test.datacenter}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_key_prefix', 'test')
        expect(config).not_to have_key('datacenter')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ namespace: 'test-value', partition: 'test-value', subkey: [{ 'key1' => 'val1' }], subkeys: { 'key1' => 'val1' }, token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_key_prefix', 'full')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
        expect(config).to have_key('subkey')
        expect(config).to have_key('subkeys')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes subkey when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('opt', required_attrs.merge(subkey: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'opt')
        expect(config).to have_key('subkey')
      end

      it 'omits subkey when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'minimal')
        expect(config).not_to have_key('subkey')
      end
      it 'includes subkeys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('opt', required_attrs.merge(subkeys: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'opt')
        expect(config).to have_key('subkeys')
      end

      it 'omits subkeys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'minimal')
        expect(config).not_to have_key('subkeys')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_key_prefix', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_key_prefix', 'typed')
        expect(config['path_prefix']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_key_prefix('first', required_attrs)
        synth.consul_key_prefix('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_key_prefix')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_key_prefix,
    method: :consul_key_prefix,
    required_attrs: { path_prefix: 'test-value' },
    expected_outputs: [:id, :datacenter],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
