# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_peering resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulPeering do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { peer_name: 'test-value', peering_token: 'test-value' } }

  describe ':consul_peering' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_peering', 'test')
        validate_required_attributes(config, [:peer_name, :peering_token])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_peering('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_peering)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_peering('test', required_attrs)

        expect(ref.id).to eq("${consul_peering.test.id}")
        expect(ref.deleted_at).to eq("${consul_peering.test.deleted_at}")
        expect(ref.peer_ca_pems).to eq("${consul_peering.test.peer_ca_pems}")
        expect(ref.peer_id).to eq("${consul_peering.test.peer_id}")
        expect(ref.peer_server_addresses).to eq("${consul_peering.test.peer_server_addresses}")
        expect(ref.peer_server_name).to eq("${consul_peering.test.peer_server_name}")
        expect(ref.state).to eq("${consul_peering.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering', 'test')
        expect(config).not_to have_key('deleted_at')
        expect(config).not_to have_key('peer_ca_pems')
        expect(config).not_to have_key('peer_id')
        expect(config).not_to have_key('peer_server_addresses')
        expect(config).not_to have_key('peer_server_name')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ meta: { 'key1' => 'val1' }, partition: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering', 'full')
        expect(config).to have_key('meta')
        expect(config).to have_key('partition')
      end
    end

    context 'optional attributes' do
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_peering', 'minimal')
        expect(config).not_to have_key('partition')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:peering_token]
        expect(sensitive_fields).to include(:peering_token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_peering', 'typed')
        expect(config['peer_name']).to be_a(String)
        expect(config['peering_token']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_peering('first', required_attrs)
        synth.consul_peering('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_peering')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_peering,
    method: :consul_peering,
    required_attrs: { peer_name: 'test-value', peering_token: 'test-value' },
    expected_outputs: [:id, :deleted_at, :peer_ca_pems, :peer_id, :peer_server_addresses, :peer_server_name, :state],
    sensitive_fields: [:peering_token],
    immutable_fields: [],
    boolean_fields: []
end
