# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_acl_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAclPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', rules: 'test-value' } }

  describe ':consul_acl_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_acl_policy', 'test')
        validate_required_attributes(config, [:name, :rules])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_acl_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_policy('test', required_attrs)

        expect(ref.id).to eq("${consul_acl_policy.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ datacenters: ['test-value'], description: 'test-value', namespace: 'test-value', partition: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_policy', 'full')
        expect(config).to have_key('datacenters')
        expect(config).to have_key('description')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition')
      end
    end

    context 'optional attributes' do
      it 'includes datacenters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('opt', required_attrs.merge(datacenters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'opt')
        expect(config).to have_key('datacenters')
      end

      it 'omits datacenters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'minimal')
        expect(config).not_to have_key('datacenters')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_policy', 'minimal')
        expect(config).not_to have_key('partition')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_policy', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['rules']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_policy('first', required_attrs)
        synth.consul_acl_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_acl_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_acl_policy,
    method: :consul_acl_policy,
    required_attrs: { name: 'test-value', rules: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
