# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_autopilot_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAutopilotConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':consul_autopilot_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_autopilot_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_autopilot_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_autopilot_config('test', required_attrs)

        expect(ref.id).to eq("${consul_autopilot_config.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cleanup_dead_servers: true, datacenter: 'test-value', disable_upgrade_migration: true, last_contact_threshold: 'test-value', max_trailing_logs: 3.14, redundancy_zone_tag: 'test-value', server_stabilization_time: 'test-value', upgrade_version_tag: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_autopilot_config', 'full')
        expect(config).to have_key('cleanup_dead_servers')
        expect(config).to have_key('datacenter')
        expect(config).to have_key('disable_upgrade_migration')
        expect(config).to have_key('last_contact_threshold')
        expect(config).to have_key('max_trailing_logs')
        expect(config).to have_key('redundancy_zone_tag')
        expect(config).to have_key('server_stabilization_time')
        expect(config).to have_key('upgrade_version_tag')
      end
    end

    context 'optional attributes' do
      it 'includes cleanup_dead_servers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(cleanup_dead_servers: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('cleanup_dead_servers')
      end

      it 'omits cleanup_dead_servers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('cleanup_dead_servers')
      end
      it 'includes datacenter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(datacenter: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('datacenter')
      end

      it 'omits datacenter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('datacenter')
      end
      it 'includes disable_upgrade_migration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(disable_upgrade_migration: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('disable_upgrade_migration')
      end

      it 'omits disable_upgrade_migration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('disable_upgrade_migration')
      end
      it 'includes last_contact_threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(last_contact_threshold: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('last_contact_threshold')
      end

      it 'omits last_contact_threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('last_contact_threshold')
      end
      it 'includes max_trailing_logs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(max_trailing_logs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('max_trailing_logs')
      end

      it 'omits max_trailing_logs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('max_trailing_logs')
      end
      it 'includes redundancy_zone_tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(redundancy_zone_tag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('redundancy_zone_tag')
      end

      it 'omits redundancy_zone_tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('redundancy_zone_tag')
      end
      it 'includes server_stabilization_time when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(server_stabilization_time: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('server_stabilization_time')
      end

      it 'omits server_stabilization_time when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('server_stabilization_time')
      end
      it 'includes upgrade_version_tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('opt', required_attrs.merge(upgrade_version_tag: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'opt')
        expect(config).to have_key('upgrade_version_tag')
      end

      it 'omits upgrade_version_tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_autopilot_config', 'minimal')
        expect(config).not_to have_key('upgrade_version_tag')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts cleanup_dead_servers=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(cleanup_dead_servers: val)
          synth.consul_autopilot_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_autopilot_config', "bool_#{val}")
          expect(config['cleanup_dead_servers']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_upgrade_migration=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_upgrade_migration: val)
          synth.consul_autopilot_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'consul_autopilot_config', "bool_#{val}")
          expect(config['disable_upgrade_migration']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_autopilot_config', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_autopilot_config('first', required_attrs)
        synth.consul_autopilot_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_autopilot_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_autopilot_config,
    method: :consul_autopilot_config,
    required_attrs: {},
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:cleanup_dead_servers, :disable_upgrade_migration]
end
