# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_node resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulNode do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { address: 'test-value', name: 'test-value' } }

  describe ':consul_node' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_node', 'test')
        validate_required_attributes(config, [:address, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_node('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_node)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_node('test', required_attrs)

        expect(ref.id).to eq("${consul_node.test.id}")
        expect(ref.datacenter).to eq("${consul_node.test.datacenter}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_node', 'test')
        expect(config).not_to have_key('datacenter')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ meta: { 'key1' => 'val1' }, partition: 'test-value', token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_node', 'full')
        expect(config).to have_key('meta')
        expect(config).to have_key('partition')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('opt', required_attrs.merge(meta: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_node', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_node', 'typed')
        expect(config['address']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_node('first', required_attrs)
        synth.consul_node('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_node')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_node,
    method: :consul_node,
    required_attrs: { address: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :datacenter],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
