# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_acl_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulAclRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':consul_acl_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_acl_role', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_acl_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_acl_role('test', required_attrs)

        expect(ref.id).to eq("${consul_acl_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', namespace: 'test-value', node_identities: [{ 'key1' => 'val1' }], partition: 'test-value', policies: ['test-value'], service_identities: [{ 'key1' => 'val1' }], templated_policies: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_role', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('namespace')
        expect(config).to have_key('node_identities')
        expect(config).to have_key('partition')
        expect(config).to have_key('policies')
        expect(config).to have_key('service_identities')
        expect(config).to have_key('templated_policies')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes node_identities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(node_identities: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('node_identities')
      end

      it 'omits node_identities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('node_identities')
      end
      it 'includes partition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(partition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('partition')
      end

      it 'omits partition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('partition')
      end
      it 'includes policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('policies')
      end

      it 'omits policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('policies')
      end
      it 'includes service_identities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(service_identities: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('service_identities')
      end

      it 'omits service_identities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('service_identities')
      end
      it 'includes templated_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('opt', required_attrs.merge(templated_policies: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'opt')
        expect(config).to have_key('templated_policies')
      end

      it 'omits templated_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_acl_role', 'minimal')
        expect(config).not_to have_key('templated_policies')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_acl_role', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_acl_role('first', required_attrs)
        synth.consul_acl_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_acl_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_acl_role,
    method: :consul_acl_role,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
