# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_config_entry_v2_exported_services resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulConfigEntryV2ExportedServices do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { kind: 'test-value', name: 'test-value', partition: 'test-value' } }

  describe ':consul_config_entry_v2_exported_services' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'test')
        validate_required_attributes(config, [:kind, :name, :partition])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_v2_exported_services('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_config_entry_v2_exported_services)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_config_entry_v2_exported_services('test', required_attrs)

        expect(ref.id).to eq("${consul_config_entry_v2_exported_services.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ namespace: 'test-value', partition_consumers: ['test-value'], peer_consumers: ['test-value'], sameness_group_consumers: ['test-value'], services: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'full')
        expect(config).to have_key('namespace')
        expect(config).to have_key('partition_consumers')
        expect(config).to have_key('peer_consumers')
        expect(config).to have_key('sameness_group_consumers')
        expect(config).to have_key('services')
      end
    end

    context 'optional attributes' do
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes partition_consumers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('opt', required_attrs.merge(partition_consumers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'opt')
        expect(config).to have_key('partition_consumers')
      end

      it 'omits partition_consumers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'minimal')
        expect(config).not_to have_key('partition_consumers')
      end
      it 'includes peer_consumers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('opt', required_attrs.merge(peer_consumers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'opt')
        expect(config).to have_key('peer_consumers')
      end

      it 'omits peer_consumers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'minimal')
        expect(config).not_to have_key('peer_consumers')
      end
      it 'includes sameness_group_consumers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('opt', required_attrs.merge(sameness_group_consumers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'opt')
        expect(config).to have_key('sameness_group_consumers')
      end

      it 'omits sameness_group_consumers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'minimal')
        expect(config).not_to have_key('sameness_group_consumers')
      end
      it 'includes services when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('opt', required_attrs.merge(services: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'opt')
        expect(config).to have_key('services')
      end

      it 'omits services when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'minimal')
        expect(config).not_to have_key('services')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_config_entry_v2_exported_services', 'typed')
        expect(config['kind']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['partition']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_config_entry_v2_exported_services('first', required_attrs)
        synth.consul_config_entry_v2_exported_services('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_config_entry_v2_exported_services')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_config_entry_v2_exported_services,
    method: :consul_config_entry_v2_exported_services,
    required_attrs: { kind: 'test-value', name: 'test-value', partition: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
