# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a consul_license resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ConsulLicense do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { license: 'test-value' } }

  describe ':consul_license' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'consul_license', 'test')
        validate_required_attributes(config, [:license])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_license('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:consul_license)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.consul_license('test', required_attrs)

        expect(ref.id).to eq("${consul_license.test.id}")
        expect(ref.customer_id).to eq("${consul_license.test.customer_id}")
        expect(ref.expiration_time).to eq("${consul_license.test.expiration_time}")
        expect(ref.features).to eq("${consul_license.test.features}")
        expect(ref.installation_id).to eq("${consul_license.test.installation_id}")
        expect(ref.issue_time).to eq("${consul_license.test.issue_time}")
        expect(ref.license_id).to eq("${consul_license.test.license_id}")
        expect(ref.product).to eq("${consul_license.test.product}")
        expect(ref.start_time).to eq("${consul_license.test.start_time}")
        expect(ref.valid).to eq("${consul_license.test.valid}")
        expect(ref.warnings).to eq("${consul_license.test.warnings}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_license', 'test')
        expect(config).not_to have_key('customer_id')
        expect(config).not_to have_key('expiration_time')
        expect(config).not_to have_key('features')
        expect(config).not_to have_key('installation_id')
        expect(config).not_to have_key('issue_time')
        expect(config).not_to have_key('license_id')
        expect(config).not_to have_key('product')
        expect(config).not_to have_key('start_time')
        expect(config).not_to have_key('valid')
        expect(config).not_to have_key('warnings')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ datacenter: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_license', 'full')
        expect(config).to have_key('datacenter')
      end
    end

    context 'optional attributes' do
      it 'includes datacenter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('opt', required_attrs.merge(datacenter: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_license', 'opt')
        expect(config).to have_key('datacenter')
      end

      it 'omits datacenter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'consul_license', 'minimal')
        expect(config).not_to have_key('datacenter')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:license]
        expect(sensitive_fields).to include(:license)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'consul_license', 'typed')
        expect(config['license']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.consul_license('first', required_attrs)
        synth.consul_license('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'consul_license')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :consul_license,
    method: :consul_license,
    required_attrs: { license: 'test-value' },
    expected_outputs: [:id, :customer_id, :expiration_time, :features, :installation_id, :issue_time, :license_id, :product, :start_time, :valid, :warnings],
    sensitive_fields: [:license],
    immutable_fields: [],
    boolean_fields: []
end
