# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/consul_config_entry_v2_exported_services/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ConsulConfigEntryV2ExportedServices
    include Pangea::Resources::ResourceBuilder

    define_resource :consul_config_entry_v2_exported_services,
      attributes_class: Consul::Types::ConfigEntryV2ExportedServicesAttributes,
      outputs: { id: :id },
      map: [:kind, :name, :partition],
      map_present: [:namespace, :partition_consumers, :peer_consumers, :sameness_group_consumers, :services]
  end
  module Consul
    include ConsulConfigEntryV2ExportedServices
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Consul)
