# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Consul::Types
  include Dry.Types()

  class ConfigEntryV2ExportedServicesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Consul::Types

    attribute :kind, T::String
    attribute :name, T::String
    attribute :partition, T::String
    attribute? :namespace, T::String.optional
    attribute? :partition_consumers, T::Array.of(T::String).optional
    attribute? :peer_consumers, T::Array.of(T::String).optional
    attribute? :sameness_group_consumers, T::Array.of(T::String).optional
    attribute? :services, T::Array.of(T::String).optional
  end
end
